In [1]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.1-cp38-cp38-win_amd64.whl (1.1 MB)
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.1

In [2]:
import psycopg2

In [127]:
#필요한 기본 DB 정보
host = "49.50.167.136" #접속할 db의 host명
user = "walker100" #접속할 db의 user명
pw = "forcebewithyou" #접속할 db의 password
db = "synthea_1000" #접속할 db의 table명 (실제 데이터가 추출되는 table)
port = 5432

In [128]:
db = psycopg2.connect(host=host, dbname=db,user=user,password=pw,port=5432)

In [129]:
cursor=db.cursor()

### 1번

In [54]:
cursor.execute("SELECT MAX(visit_end_date - visit_start_date +1) FROM visit_occurrence;")
cursor.fetchall()

[(3731,)]

In [55]:
cursor.execute("SELECT count(*) FROM visit_occurrence WHERE visit_end_date - visit_start_date +1 = (SELECT MAX(visit_end_date - visit_start_date +1) FROM visit_occurrence);")
cursor.fetchall()

[(1,)]

In [43]:
cursor.execute("SELECT condition_concept_id FROM condition_occurrence;")
cursor.fetchall()

[(0,),
 (0,),
 (81151,),
 (260139,),
 (312437,),
 (314754,),
 (4079750,),
 (4223659,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (81151,),
 (254761,),
 (260139,),
 (312437,),
 (314754,),
 (378253,),
 (434490,),
 (4112853,),
 (4289517,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (260139,),
 (312437,),
 (314754,),
 (437663,),
 (4112343,),
 (4147326,),
 (37311061,),
 (40481087,),
 (0,),
 (312437,),
 (314754,),
 (437663,),
 (4089228,),
 (4223659,),
 (4289517,),
 (37311061,),
 (0,),
 (78272,),
 (81151,),
 (254761,),
 (312437,),
 (314754,),
 (372328,),
 (372328,),
 (437663,),
 (37311061,),
 (40481087,),
 (40486433,),
 (0,),
 (254761,),
 (378253,),
 (437663,),
 (4089228,),
 (4223659,),
 (37311061,),
 (81151,),
 (439393,),
 (439777,),
 (4078393,),
 (4217975,),
 (4217975,),
 (4217975,),
 (4217975,),
 (4217975,),
 (4262136,),
 (0,),
 (255848,),
 (260139,),
 (372328,),
 (437390,),
 (437663,),
 (4158346,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (45768439,),
 (0,),
 (0,),
 (260139,),
 (378001,),
 (437663,),
 (4218389,),
 (4289517,),
 (37311061,),
 (0,),
 (75036,),
 (199076,),
 (255848,),
 (257012,),
 (320128,),
 (378419,),
 (432867,),
 (4078393,),
 (4112343,),
 (4285898,),
 (4285898,),
 (4309027,),
 (37017023,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (255848,),
 (260139,),
 (319049,),
 (320128,),
 (434490,),
 (437390,),
 (4158346,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (44782746,),
 (260139,),
 (261325,),
 (4311629,),
 (0,),
 (254761,),
 (372328,),
 (372328,),
 (437663,),
 (4089228,),
 (4147326,),
 (37311061,),
 (75036,),
 (192279,),
 (201826,),
 (257012,),
 (436940,),
 (439777,),
 (443614,),
 (4120314,),
 (4229440,),
 (4278672,),
 (40481087,),
 (0,),
 (260139,),
 (378253,),
 (437663,),
 (4078393,),
 (4147326,),
 (4195085,),
 (4217975,),
 (4217975,),
 (4217975,),
 (37311061,),
 (40318618,),
 (40481087,),
 (40486433,),
 (0,),
 (437663,),
 (4089228,),
 (4112343,),
 (4223659,),
 (37311061,),
 (40481087,),
 (0,),
 (439777,),
 (4112343,),
 (4112343,),
 (4112343,),
 (4112343,),
 (4311629,),
 (40481087,),
 (0,),
 (0,),
 (260139,),
 (260139,),
 (438130,),
 (4094814,),
 (0,),
 (0,),
 (78272,),
 (78272,),
 (201826,),
 (255848,),
 (312437,),
 (314754,),
 (319049,),
 (320128,),
 (432867,),
 (436940,),
 (437390,),
 (437663,),
 (439777,),
 (4112343,),
 (4112343,),
 (4120314,),
 (4134304,),
 (4158346,),
 (4214376,),
 (4223659,),
 (4226121,),
 (4311629,),
 (36674642,),
 (37016354,),
 (37311061,),
 (40481087,),
 (40481087,),
 (43530656,),
 (45768439,),
 (45770830,),
 (0,),
 (254761,),
 (260139,),
 (312437,),
 (314754,),
 (437663,),
 (4089228,),
 (4145808,),
 (4289517,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (254761,),
 (378001,),
 (437663,),
 (4089228,),
 (4112343,),
 (4223659,),
 (37311061,),
 (40481087,),
 (0,),
 (81151,),
 (254761,),
 (434490,),
 (437663,),
 (439777,),
 (4078393,),
 (4089228,),
 (4112343,),
 (4147326,),
 (4223659,),
 (4289517,),
 (4311629,),
 (40481087,),
 (0,),
 (0,),
 (77074,),
 (78272,),
 (78272,),
 (81151,),
 (201826,),
 (254761,),
 (255848,),
 (260139,),
 (320128,),
 (437390,),
 (437663,),
 (439777,),
 (440448,),
 (442752,),
 (4078393,),
 (4120314,),
 (4155034,),
 (4158346,),
 (4166224,),
 (4217975,),
 (4289517,),
 (37311061,),
 (40318618,),
 (0,),
 (0,),
 (0,),
 (31967,),
 (81151,),
 (195588,),
 (254761,),
 (257012,),
 (260139,),
 (312437,),
 (314754,),
 (378253,),
 (437663,),
 (440448,),
 (4096715,),
 (4112343,),
 (4217975,),
 (4217975,),
 (4217975,),
 (4223659,),
 (4283893,),
 (37311061,),
 (40481087,),
 (0,),
 (133834,),
 (254761,),
 (260139,),
 (372328,),
 (434490,),
 (437663,),
 (37311061,),
 (0,),
 (81151,),
 (254761,),
 (260139,),
 (260139,),
 (437663,),
 (4278672,),
 (37311061,),
 (0,),
 (254761,),
 (260139,),
 (437663,),
 (4149245,),
 (4223659,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (255848,),
 (317576,),
 (437390,),
 (437663,),
 (4112343,),
 (4112343,),
 (4112343,),
 (4158346,),
 (4223659,),
 (4229440,),
 (4289517,),
 (4296204,),
 (37311061,),
 (200970,),
 (257012,),
 (313217,),
 (320128,),
 (438130,),
 (439777,),
 (4112343,),
 (4129902,),
 (4218106,),
 (4229440,),
 (4311629,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (257012,),
 (312437,),
 (314754,),
 (320128,),
 (437663,),
 (438130,),
 (439777,),
 (4112343,),
 (4311629,),
 (37311061,),
 (0,),
 (28060,),
 (372328,),
 (378253,),
 (437663,),
 (4089228,),
 (37311061,),
 (40481087,),
 (0,),
 (28060,),
 (28060,),
 (260139,),
 (260139,),
 (317576,),
 (372328,),
 (4329847,),
 (0,),
 (254761,),
 (260139,),
 (260139,),
 (439777,),
 (4079750,),
 (4112343,),
 (4113008,),
 (4218389,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (199076,),
 (255848,),
 (260139,),
 (313217,),
 (317576,),
 (378419,),
 (432867,),
 (4029498,),
 (4078393,),
 (4311629,),
 (0,),
 (0,),
 (81151,),
 (317576,),
 (439777,),
 (4112343,),
 (4112343,),
 (4113008,),
 (4311629,),
 (4329847,),
 (0,),
 (0,),
 (317576,),
 (378001,),
 (4112343,),
 (4218106,),
 (4329847,),
 (0,),
 (0,),
 (254761,),
 (320128,),
 (434490,),
 (437663,),
 (439777,),
 (4079749,),
 (4089228,),
 (4112343,),
 (4156265,),
 (4218389,),
 (4223659,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (320128,),
 (432867,),
 (434490,),
 (437663,),
 (4078393,),
 (4112343,),
 (4112343,),
 (4112343,),
 (4156265,),
 (4223659,),
 (37311061,),
 (40486433,),
 (0,),
 (4078393,),
 (4152936,),
 (0,),
 (0,),
 (80502,),
 (381316,),
 (432867,),
 (437663,),
 (4089228,),
 (4112343,),
 (4145808,),
 (4230399,),
 (4289517,),
 (4296205,),
 (37311061,),
 (40480160,),
 (40481087,),
 (0,),
 (77074,),
 (260139,),
 (437663,),
 (442752,),
 (4283893,),
 (4289517,),
 (37311061,),
 (40481087,),
 (0,),
 (199076,),
 (254761,),
 (320128,),
 (437663,),
 (439777,),
 (4078393,),
 (4089228,),
 (4147326,),
 (4223659,),
 (4285898,),
 (4311629,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (77074,),
 (260139,),
 (320128,),
 (434490,),
 (437663,),
 (442752,),
 (4089228,),
 (4142905,),
 (37311061,),
 (0,),
 (0,),
 (320128,),
 (437663,),
 (4089228,),
 (4112343,),
 (4217975,),
 (4217975,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (0,),
 (77074,),
 (255848,),
 (257012,),
 (437390,),
 (437663,),
 (440448,),
 (442752,),
 (4079750,),
 (4112343,),
 (4158346,),
 (4195085,),
 (4289517,),
 (37311061,),
 (0,),
 (28060,),
 (254761,),
 (320128,),
 (372328,),
 (378253,),
 (437663,),
 (37311061,),
 (0,),
 (0,),
 (77074,),
 (254761,),
 (260139,),
 (375671,),
 (437663,),
 (442752,),
 (4089228,),
 (4223659,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (134438,),
 (255848,),
 (257012,),
 (260139,),
 (260139,),
 (319049,),
 (320128,),
 (434490,),
 (437390,),
 (437663,),
 (4147326,),
 (4155034,),
 (4158346,),
 (4223659,),
 (4283893,),
 (37311061,),
 (0,),
 (78272,),
 (81151,),
 (254761,),
 (260139,),
 (260139,),
 (378253,),
 (437663,),
 (4059173,),
 (4156265,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (260139,),
 (439777,),
 (4195085,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (0,),
 (254761,),
 (257012,),
 (260139,),
 (437663,),
 (4145808,),
 (4230399,),
 (4283893,),
 (37311061,),
 (0,),
 (254761,),
 (260139,),
 (320128,),
 (437663,),
 (439777,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (77074,),
 (437663,),
 (442752,),
 (4078393,),
 (4079750,),
 (4112343,),
 (4311629,),
 (37311061,),
 (0,),
 (254761,),
 (257012,),
 (434490,),
 (4112343,),
 (4149245,),
 (4155034,),
 (4223659,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (195588,),
 (195588,),
 (255848,),
 (260139,),
 (437390,),
 (437663,),
 (4112343,),
 (4116491,),
 (4158346,),
 (4217975,),
 (4217975,),
 (4217975,),
 (37311061,),
 (0,),
 (77074,),
 (254761,),
 (257012,),
 (437663,),
 (442752,),
 (4112343,),
 (4112343,),
 (4112343,),
 (4113008,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (437663,),
 (4079749,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (28060,),
 (437663,),
 (4078393,),
 (4112343,),
 (4289517,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (77074,),
 (81151,),
 (254761,),
 (380378,),
 (437663,),
 (439777,),
 (442752,),
 (4029498,),
 (4078393,),
 (4112343,),
 (4195085,),
 (4289517,),
 (4296205,),
 (4311629,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (4084167,),
 (4112343,),
 (4278672,),
 (40481087,),
 (40486433,),
 (0,),
 (0,),
 (254761,),
 (255848,),
 (260139,),
 (312437,),
 (314754,),
 (375671,),
 (432867,),
 (437390,),
 (437663,),
 (439777,),
 (4078393,),
 (4079750,),
 (4112343,),
 (4158346,),
 (4223659,),
 (4237458,),
 (4285898,),
 (4289517,),
 (4316217,),
 (36674642,),
 (37311061,),
 (45768439,),
 (0,),
 (0,),
 (77074,),
 (81151,),
 (254761,),
 (378253,),
 (437663,),
 (442752,),
 (4109685,),
 (4112343,),
 (4155034,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (0,),
 (254761,),
 (257012,),
 (260139,),
 (317576,),
 (320128,),
 (437663,),
 (4079750,),
 (4283893,),
 (4285898,),
 (4329847,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (260139,),
 (378253,),
 (437663,),
 (4079750,),
 (4089228,),
 (4112343,),
 (4112343,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (81151,),
 (192279,),
 (201826,),
 (254761,),
 (320128,),
 (436940,),
 (437663,),
 (439777,),
 (443614,),
 (4120314,),
 (4237458,),
 (4289517,),
 (37311061,),
 (0,),
 (77074,),
 (254761,),
 (260139,),
 (437663,),
 (442752,),
 (4089228,),
 (4113008,),
 (4134304,),
 (4147326,),
 (4155034,),
 (4223659,),
 (4280726,),
 (4289517,),
 (37311061,),
 (40481087,),
 (0,),
 (254761,),
 (4147326,),
 (4217975,),
 (4289517,),
 (37311061,),
 (0,),
 (260139,),
 (436096,),
 (4078393,),
 (4079750,),
 (4112853,),
 (4208104,),
 (43530652,),
 (0,),
 (0,),
 (254761,),
 (372328,),
 (437663,),
 (4112343,),
 (4223659,),
 (4289517,),
 (37311061,),
 (40481087,),
 (4094814,),
 (40481087,),
 (0,),
 (254761,),
 (437663,),
 (4223659,),
 (37311061,),
 (0,),
 (0,),
 (77074,),
 (254761,),
 (257012,),
 (260139,),
 (440448,),
 (442752,),
 (4089228,),
 (4166224,),
 (37311061,),
 (40481087,),
 (0,),
 (0,),
 (28060,),
 (77074,),
 (254761,),
 (257012,),
 (260139,),
 (437663,),
 (442752,),
 (4223659,),
 (4285898,),
 (40481087,),
 (40481087,),
 (78272,),
 (80502,),
 (257012,),
 (320128,),
 (378419,),
 (381316,),
 (4059173,),
 (4218389,),
 (4230399,),
 (40480160,),
 (40481087,),
 (40481087,),
 (40481087,),
 (0,),
 (317576,),
 (4112343,),
 (4112343,),
 (4329847,),
 (40481087,),
 (0,),
 (0,),
 (254761,),
 (437663,),
 (4089228,),
 (4112343,),
 (37311061,),
 (0,),
 (0,),
 (28060,),
 (254761,),
 (255848,),
 (260139,),
 (312437,),
 (314754,),
 (320128,),
 (378253,),
 (432867,),
 (437390,),
 (437663,),
 (4079750,),
 (4112343,),
 (4158346,),
 (4223659,),
 (36674642,),
 (37311061,),
 (40481087,),
 (44782746,),
 (0,),
 (0,),
 (199076,),
 (255848,),
 (378253,),
 (437390,),
 (437663,),
 (439777,),
 (4078393,),
 (4089228,),
 (4116491,),
 (4158346,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (40481087,),
 (40481087,),
 (40481087,),
 (45768439,),
 (4112343,),
 (0,),
 (0,),
 (257012,),
 (437663,),
 (4112343,),
 (4289517,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (0,),
 (28060,),
 (260139,),
 (260139,),
 (437663,),
 (4112343,),
 (4112343,),
 (4147326,),
 (4223659,),
 (4278672,),
 (37311061,),
 (40481087,),
 (40481087,),
 (0,),
 (31967,),
 (437663,),
 (439777,),
 (4096715,),
 (4112343,),
 (4217975,),
 (4218389,),
 (4223659,),
 (4289517,),
 (4311629,),
 (37311061,),
 (0,),
 (77074,),
 (254761,),
 (255848,),
 (260139,),
 (260139,),
 (312437,),
 (314754,),
 (319049,),
 (437390,),
 (437663,),
 (439777,),
 (442752,),
 (4112343,),
 (4112343,),
 (4158346,),
 (4289517,),
 (4311629,),
 (37311061,),
 (40481087,),
 (44782746,),
 (192279,),
 (200970,),
 (201826,),
 (260139,),
 (320128,),
 (378419,),
 (436940,),
 (439777,),
 (443601,),
 (4120314,),
 (4129902,),
 ...]

### 2번

In [81]:
cursor.execute("SELECT DISTINCT c.concept_name FROM concept AS c \
                JOIN condition_occurrence AS co \
                ON co.condition_concept_id = c.concept_id \
                WHERE c.concept_name LIKE '%heart%' AND (\
               (c.concept_name LIKE 'a%') OR (c.concept_name LIKE 'A%') OR \
               (c.concept_name LIKE 'b%') OR (c.concept_name LIKE 'B%') OR \
               (c.concept_name LIKE 'c%') OR (c.concept_name LIKE 'C%') OR \
               (c.concept_name LIKE 'd%') OR (c.concept_name LIKE 'D%') OR \
               (c.concept_name LIKE 'e%') OR (c.concept_name LIKE 'E%'));")
cursor.fetchall()

[('Chronic congestive heart failure',)]

### 3번

In [156]:
cursor.execute("SELECT drug_concept_id, drug_exposure_start_date,drug_exposure_end_date  \
                FROM drug_exposure WHERE person_id = '1891866' GROUP BY drug_concept_id;")
cursor.fetchall()

[(40213154,), (1539463,), (40213227,), (19009384,), (19030765,)]

In [157]:
'''
1.datetime 형식을 바꾸는 방법
2.datetime을 string으로 인식 후 y-m-d 형식으로 변환
3.Group by drug_concept_id 로 그룹화
4.Order (By 새롭게 계산한 칼럼 = 종료일 - 시작일) DESC
'''

'\n1.datetime 형식을 바꾸는 방법\n2.datetime을 string으로 인식 후 y-m-d 형식으로 변환\n3.Group by drug_concept_id 로 그룹화\n4.Order (By 새롭게 계산한 칼럼 = 종료일 - 시작일) DESC\n'

### 4번

In [ ]:
cursor.execute("SELECT drug_concept_id, drug_exposure_start_date,drug_exposure_end_date  \
                FROM drug_exposure WHERE person_id = '1891866' GROUP BY drug_concept_id;")
cursor.fetchall()

### 5번

In [162]:
cursor.execute("SELECT * FROM condition_occurrence \
                WHERE condition_concept_id in (3191208,36684827,3194332,3193274,43531010,\
                4130162,45766052,45757474,4099651,4129519,4063043,4230254,4193704,4304377,\
                201826,3194082,3192767) ;")
cursor.fetchall()

[(18852812,
  1496597,
  201826,
  datetime.date(2003, 6, 25),
  datetime.datetime(2003, 6, 25, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  118098027,
  0,
  '44054006',
  201826,
  None),
 (391684,
  31196,
  201826,
  datetime.date(1983, 2, 3),
  datetime.datetime(1983, 2, 3, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  25713132,
  0,
  '44054006',
  201826,
  None),
 (28897593,
  2293584,
  201826,
  datetime.date(2018, 10, 7),
  datetime.datetime(2018, 10, 7, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  87633778,
  0,
  '44054006',
  201826,
  None),
 (29253135,
  2321793,
  201826,
  datetime.date(2016, 1, 19),
  datetime.datetime(2016, 1, 19, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  40870122,
  0,
  '44054006',
  201826,
  None),
 (17065310,
  1354811,
  201826,
  datetime.date(1970, 4, 24),
  datetime.datetime(1970, 4, 24, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  102058365,
  0,
  '44054006',
  201826,
  None),
 (31973916,
  2537704,
  201826,
  datetime.date(1975, 2, 17),
  datetime.datetime(1975, 2, 17, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  27123243,
  0,
  '44054006',
  201826,
  None),
 (7674541,
  609120,
  201826,
  datetime.date(1988, 3, 27),
  datetime.datetime(1988, 3, 27, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  72756804,
  0,
  '44054006',
  201826,
  None),
 (30252464,
  2400845,
  201826,
  datetime.date(2016, 6, 4),
  datetime.datetime(2016, 6, 4, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  100562269,
  0,
  '44054006',
  201826,
  None),
 (22953560,
  1821726,
  201826,
  datetime.date(1998, 9, 24),
  datetime.datetime(1998, 9, 24, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  68571932,
  0,
  '44054006',
  201826,
  None),
 (26136464,
  2074366,
  201826,
  datetime.date(1995, 4, 29),
  datetime.datetime(1995, 4, 29, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  94941101,
  0,
  '44054006',
  201826,
  None),
 (19263097,
  1529132,
  201826,
  datetime.date(2014, 4, 5),
  datetime.datetime(2014, 4, 5, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  22315336,
  0,
  '44054006',
  201826,
  None),
 (11451942,
  909084,
  201826,
  datetime.date(1987, 1, 2),
  datetime.datetime(1987, 1, 2, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  99772829,
  0,
  '44054006',
  201826,
  None),
 (26504260,
  2103544,
  201826,
  datetime.date(1990, 1, 15),
  datetime.datetime(1990, 1, 15, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  105718937,
  0,
  '44054006',
  201826,
  None),
 (22923470,
  1819367,
  201826,
  datetime.date(1960, 9, 10),
  datetime.datetime(1960, 9, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  119590253,
  0,
  '44054006',
  201826,
  None),
 (27011372,
  2143829,
  201826,
  datetime.date(1994, 7, 20),
  datetime.datetime(1994, 7, 20, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  82849746,
  0,
  '44054006',
  201826,
  None),
 (29854602,
  2369278,
  201826,
  datetime.date(1956, 10, 13),
  datetime.datetime(1956, 10, 13, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  119869100,
  0,
  '44054006',
  201826,
  None),
 (6144523,
  487607,
  201826,
  datetime.date(2016, 11, 29),
  datetime.datetime(2016, 11, 29, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  60326164,
  0,
  '44054006',
  201826,
  None),
 (23019295,
  1826955,
  201826,
  datetime.date(2018, 7, 25),
  datetime.datetime(2018, 7, 25, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  63233704,
  0,
  '44054006',
  201826,
  None),
 (8273178,
  656683,
  201826,
  datetime.date(2017, 7, 7),
  datetime.datetime(2017, 7, 7, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  40956945,
  0,
  '44054006',
  201826,
  None),
 (4380078,
  347825,
  201826,
  datetime.date(1989, 2, 3),
  datetime.datetime(1989, 2, 3, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  90639378,
  0,
  '44054006',
  201826,
  None),
 (13887125,
  1102377,
  201826,
  datetime.date(2007, 4, 3),
  datetime.datetime(2007, 4, 3, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  98853958,
  0,
  '44054006',
  201826,
  None),
 (16598158,
  1317600,
  201826,
  datetime.date(2012, 6, 28),
  datetime.datetime(2012, 6, 28, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  37017839,
  0,
  '44054006',
  201826,
  None),
 (6699802,
  531690,
  201826,
  datetime.date(1975, 3, 13),
  datetime.datetime(1975, 3, 13, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  127243609,
  0,
  '44054006',
  201826,
  None),
 (19883315,
  1578321,
  201826,
  datetime.date(1962, 4, 16),
  datetime.datetime(1962, 4, 16, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  34973006,
  0,
  '44054006',
  201826,
  None),
 (29632573,
  2351697,
  201826,
  datetime.date(1997, 12, 19),
  datetime.datetime(1997, 12, 19, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  79890436,
  0,
  '44054006',
  201826,
  None),
 (18537964,
  1471705,
  201826,
  datetime.date(1992, 3, 18),
  datetime.datetime(1992, 3, 18, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  131441867,
  0,
  '44054006',
  201826,
  None),
 (844868,
  67212,
  201826,
  datetime.date(2004, 12, 9),
  datetime.datetime(2004, 12, 9, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  53391660,
  0,
  '44054006',
  201826,
  None),
 (10630242,
  843873,
  201826,
  datetime.date(1987, 2, 17),
  datetime.datetime(1987, 2, 17, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  21696581,
  0,
  '44054006',
  201826,
  None),
 (21895362,
  1737916,
  201826,
  datetime.date(2006, 1, 24),
  datetime.datetime(2006, 1, 24, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  48152330,
  0,
  '44054006',
  201826,
  None),
 (19811292,
  1572626,
  201826,
  datetime.date(1990, 10, 3),
  datetime.datetime(1990, 10, 3, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  80440802,
  0,
  '44054006',
  201826,
  None),
 (24471624,
  1942103,
  201826,
  datetime.date(1960, 5, 1),
  datetime.datetime(1960, 5, 1, 1, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  47385579,
  0,
  '44054006',
  201826,
  None),
 (21960747,
  1743075,
  201826,
  datetime.date(1960, 2, 7),
  datetime.datetime(1960, 2, 7, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  90259867,
  0,
  '44054006',
  201826,
  None),
 (2142358,
  170280,
  201826,
  datetime.date(1995, 1, 28),
  datetime.datetime(1995, 1, 28, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  88146923,
  0,
  '44054006',
  201826,
  None),
 (637191,
  50663,
  201826,
  datetime.date(2012, 12, 4),
  datetime.datetime(2012, 12, 4, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  116959976,
  0,
  '44054006',
  201826,
  None),
 (24949795,
  1979909,
  201826,
  datetime.date(2014, 6, 19),
  datetime.datetime(2014, 6, 19, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  24309616,
  0,
  '44054006',
  201826,
  None),
 (6772952,
  537462,
  201826,
  datetime.date(1995, 10, 28),
  datetime.datetime(1995, 10, 28, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  72426396,
  0,
  '44054006',
  201826,
  None),
 (32478871,
  2577809,
  201826,
  datetime.date(1946, 6, 3),
  datetime.datetime(1946, 6, 3, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  72712403,
  0,
  '44054006',
  201826,
  None),
 (6429214,
  510173,
  201826,
  datetime.date(1997, 4, 23),
  datetime.datetime(1997, 4, 23, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  87012668,
  0,
  '44054006',
  201826,
  None),
 (6030521,
  478532,
  201826,
  datetime.date(1970, 7, 15),
  datetime.datetime(1970, 7, 15, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  128195749,
  0,
  '44054006',
  201826,
  None),
 (14065173,
  1116539,
  201826,
  datetime.date(1994, 7, 10),
  datetime.datetime(1994, 7, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  107646208,
  0,
  '44054006',
  201826,
  None),
 (11834073,
  939449,
  201826,
  datetime.date(2018, 2, 10),
  datetime.datetime(2018, 2, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  28118139,
  0,
  '44054006',
  201826,
  None),
 (17869973,
  1418681,
  201826,
  datetime.date(1995, 7, 2),
  datetime.datetime(1995, 7, 2, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  79946124,
  0,
  '44054006',
  201826,
  None),
 (30905198,
  2452672,
  201826,
  datetime.date(2009, 5, 21),
  datetime.datetime(2009, 5, 21, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  92676198,
  0,
  '44054006',
  201826,
  None),
 (19374172,
  1537987,
  201826,
  datetime.date(1950, 12, 10),
  datetime.datetime(1950, 12, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  99356123,
  0,
  '44054006',
  201826,
  None),
 (6250153,
  495973,
  201826,
  datetime.date(1996, 4, 17),
  datetime.datetime(1996, 4, 17, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  39720131,
  0,
  '44054006',
  201826,
  None),
 (18200346,
  1444791,
  201826,
  datetime.date(1973, 1, 20),
  datetime.datetime(1973, 1, 20, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  69486769,
  0,
  '44054006',
  201826,
  None),
 (11238731,
  892185,
  201826,
  datetime.date(2015, 8, 20),
  datetime.datetime(2015, 8, 20, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  96762902,
  0,
  '44054006',
  201826,
  None),
 (33949243,
  2694671,
  201826,
  datetime.date(1977, 5, 26),
  datetime.datetime(1977, 5, 26, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  23969879,
  0,
  '44054006',
  201826,
  None),
 (6538717,
  518868,
  201826,
  datetime.date(1948, 10, 11),
  datetime.datetime(1948, 10, 11, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  40828451,
  0,
  '44054006',
  201826,
  None),
 (35704969,
  2833968,
  201826,
  datetime.date(1947, 1, 6),
  datetime.datetime(1947, 1, 6, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  48525034,
  0,
  '44054006',
  201826,
  None),
 (2221995,
  176640,
  201826,
  datetime.date(2010, 10, 10),
  datetime.datetime(2010, 10, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  67153078,
  0,
  '44054006',
  201826,
  None),
 (14292868,
  1134605,
  201826,
  datetime.date(2018, 2, 27),
  datetime.datetime(2018, 2, 27, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  49739783,
  0,
  '44054006',
  201826,
  None),
 (18224970,
  1446772,
  201826,
  datetime.date(1988, 12, 10),
  datetime.datetime(1988, 12, 10, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  100483566,
  0,
  '44054006',
  201826,
  None),
 (23839778,
  1891866,
  201826,
  datetime.date(1956, 3, 21),
  datetime.datetime(1956, 3, 21, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  27064134,
  0,
  '44054006',
  201826,
  None),
 (27343335,
  2170146,
  201826,
  datetime.date(1970, 2, 18),
  datetime.datetime(1970, 2, 18, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  45661668,
  0,
  '44054006',
  201826,
  None),
 (7951750,
  631283,
  201826,
  datetime.date(1992, 6, 25),
  datetime.datetime(1992, 6, 25, 0, 0),
  None,
  None,
  32020,
  0,
  None,
  None,
  74926242,
  0,
  '44054006',
  201826,
  None)]

[('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_occurrence_id',
  1,
  None,
  'NO',
  'bigint',
  None,
  None,
  64,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int8',
  None,
  None,
  None,
  None,
  '1',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'person_id',
  2,
  None,
  'YES',
  'bigint',
  None,
  None,
  64,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int8',
  None,
  None,
  None,
  None,
  '2',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_concept_id',
  3,
  None,
  'YES',
  'integer',
  None,
  None,
  32,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int4',
  None,
  None,
  None,
  None,
  '3',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_start_date',
  4,
  None,
  'YES',
  'date',
  None,
  None,
  None,
  None,
  None,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'date',
  None,
  None,
  None,
  None,
  '4',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_start_datetime',
  5,
  None,
  'YES',
  'timestamp without time zone',
  None,
  None,
  None,
  None,
  None,
  6,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'timestamp',
  None,
  None,
  None,
  None,
  '5',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_end_date',
  6,
  None,
  'YES',
  'date',
  None,
  None,
  None,
  None,
  None,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'date',
  None,
  None,
  None,
  None,
  '6',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_end_datetime',
  7,
  None,
  'YES',
  'timestamp without time zone',
  None,
  None,
  None,
  None,
  None,
  6,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'timestamp',
  None,
  None,
  None,
  None,
  '7',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_type_concept_id',
  8,
  None,
  'YES',
  'integer',
  None,
  None,
  32,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int4',
  None,
  None,
  None,
  None,
  '8',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_status_concept_id',
  9,
  None,
  'YES',
  'integer',
  None,
  None,
  32,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int4',
  None,
  None,
  None,
  None,
  '9',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'visit_occurrence_id',
  12,
  None,
  'YES',
  'bigint',
  None,
  None,
  64,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int8',
  None,
  None,
  None,
  None,
  '12',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'visit_detail_id',
  13,
  None,
  'YES',
  'bigint',
  None,
  None,
  64,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int8',
  None,
  None,
  None,
  None,
  '13',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_source_concept_id',
  15,
  None,
  'YES',
  'integer',
  None,
  None,
  32,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int4',
  None,
  None,
  None,
  None,
  '15',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'provider_id',
  11,
  None,
  'YES',
  'bigint',
  None,
  None,
  64,
  2,
  0,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'int8',
  None,
  None,
  None,
  None,
  '11',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'stop_reason',
  10,
  None,
  'YES',
  'character varying',
  20,
  80,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'varchar',
  None,
  None,
  None,
  None,
  '10',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_status_source_value',
  16,
  None,
  'YES',
  'character varying',
  50,
  200,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'varchar',
  None,
  None,
  None,
  None,
  '16',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES'),
 ('synthea_1000',
  'de',
  'condition_occurrence',
  'condition_source_value',
  14,
  None,
  'YES',
  'character varying',
  50,
  200,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'synthea_1000',
  'pg_catalog',
  'varchar',
  None,
  None,
  None,
  None,
  '14',
  'NO',
  'NO',
  None,
  None,
  None,
  None,
  None,
  'NO',
  'NEVER',
  None,
  'YES')]

In [174]:
db.commit()